FROM python:2

WORKDIR /src

#ADD ./bin/* /bin/
ADD ./src/*.py /src/
ADD ./src/kafka_consumer/*.py /src/kafka_consumer/
ADD ./src/utilities/*.py /src/utilities/

RUN pip install kafka-python

ENV TOPIC_NAME=test
ENV CONSUMER_BOOTSTRAP=10.0.2.15:9092
#ENV CONSUMER_BOOTSTRAP=192.168.122.1:9092

#CMD [ "bash", "pythonConsumer.sh"]
CMD [ "python", "to84-consumer.py"]
